- ddl.dic
Correcting a few misspelt words.
> Correcting a few typos.

- cif_core.dic
Content type of the '_audit.creation_date' data item was content type of the '_audit.creation_date' data item was changed from 'Date' to 'DateTime' and the description was updated accordingly.
> Changed: content type of the '_audit.creation_date' data item was changed to 'DateTime'

- ddl.dic
Updated the description of the _description_example.case data item.
This PR solves issue #114.
> Update of the _description_example.case data item description.

- ddl.dic
> Updated the definition of the _import_details.mode data item

- cif_core.dic
Corrected the definitions of the `_cell_measurement.temperature_su` and `_cell_measurement.pressure_su` data items.
> Corrected the definitions of several data item

- cif_core.dic
- cif_ms.dic
Several data item were slightly modified ('identifyed in' -> 'identified by').
> Fixed: corrected a typo in several data item definitions

- cif_core.dic
- cif_img.dic
- cif_ms.dic
- cif_pow.dic
- ddl.dic
- templ_attr.cif
Simply pulling in some final updates that applied to cif2-conversion.
> Merge updates that remove Index and Count types

- templ_enum.cif
Kelvins are not measured in degrees.
> Fixed: corrected the usage of the kelvin measurement units 

- cif_core.dic
> Added special details for audit_author_role

- templ_attr.cif
- templ_enum.cif
This PR fixes a few typos in the template files.
> Fix typos in template files

- ddl.dic
> Clarify status of attributes not mentioned in dictionary_valid loop.

- cif_core.dic
- templ_attr.cif
This PR addresses issues #206 and #207.
> Fix coordinate matrix unit of measurement

- templ_enum.cif
This PR resolves issue #239 by adding deuterium as a separate "element" as suggested in the issue discussion.
> Add deuterium as an element

- cif_core.dic
> Add enumeration range to _space_group_Wyckoff.multiplicity

- cif_core.dic
> Fix definitions for b_iso and u_iso.

- cif_core.dic
> Update data name capitalisation

- .github/workflows/main.yml
This pull request updates the 'layout' part of the checking workflow to cache the julia setup, saving over a minute due to avoiding downloading and precompilation. This also dependence on the previously-used action from the workflow.
> Updated checking workflow to allow caching.

- cif_core.dic
- templ_attr.cif
> Changed atomic labels to type 'Word' for conformance with DDL1

- ddl.dic
> Added detailed explanation of 'Replace' if_dupl mode for importation.

- ddl.dic
> Improved clarity of 'Implied' content and container descriptions.

- .github/workflows/main.yml
- templ_enum.cif
Add units used in imgCIF dictionary to main units list.
Update workflow to use later version of linting software.
> More units

- templ_enum.cif
> Correct the descriptions of electron density units.

- cif_core.dic
- templ_enum.cif
Addresses #234 
The examples given are a poor copy/paste from the examples of @vaitkus . Will probably need to be changed.
> add the _exptl_absorpt.special_details data item

- ddl.dic
Sentences now start with a capital letter, end with a full stop. Previously, they were a mixture.
> formatted _enumeration_set.detail values to be sentences.

- ddl.dic
Will close #280 
Previously, zero was excluded.
> Define "integer" to include zero.

- cif_core.dic
In a few cases the URLs were also slightly adjusted or additional URL (e.g. with DOIs) added.
> Change the scheme part in multiple URLs from 'http' to 'https'

- cif_core.dic
> Change the purpose of _diffrn_radiation_wavelength.id from 'Encode' to 'Key'

- cif_core.dic
- templ_attr.cif
- templ_enum.cif
From https://github.com/COMCIFS/cif_core/pull/381#issuecomment-1543249332: saveframe names are supposed to be lower case.
> lowercased all the save frame names

- templ_enum.cif
Added the missing new elements and realphabetised the list.
> Add missing element symbols

- cif_core.dic
- templ_attr.cif
> Add the default value of '1_555' to the site symmetry data items

- cif_core.dic
- templ_attr.cif
to follow guidance in https://github.com/COMCIFS/comcifs.github.io/issues/19 and https://github.com/COMCIFS/comcifs.github.io/issues/22
> Format enumeration ranges

- cif_core.dic
> Change parent category from ATOM_ANALYTICAL to ATOM.

- cif_core.dic
- templ_attr.cif
SU data items are all of type `Related`.
Edit: remove the linking to issue #433
> SUs are all related

- ddl.dic
> Specify related type source usage with SU items

- templ_attr.cif
This PR includes all changes from the 'modulated-development' branch for the files that are still in this repository. It is unlikely that the branch will be merged in the conventional way due to the repository being split into multiple smaller repositories, so I wanted to highlight the changes that still apply to this repository. Note that some of the changes might no longer be relevant (e.g. the default values are now quite discouraged by the IUCr).
> Add changes from the 'modulated-development' branch.

- ddl.dic
This PR fixes a minor stylistic issue in the description of the `State` purpose.
> Update description of the 'State' purpose

- cif_core.dic
This PR fully completes the SU definitions standardisation started with PR #440.
> Replace general SU attributes with import statements

- cif_core.dic
- templ_attr.cif
> Change the enumeration range of in the 'cell_length' save frame from to '0.0:'

- cif_core.dic
> Split and deprecate publ contact author

- cif_core.dic
A minor typo correction. Could not commit directly due to branch protection rules (good!).
> Add missing full stop

- cif_core.dic
- templ_enum.cif
Definitions suggested by the electron diffraction (cif_ed) group and reviewed via coredmg mailing list and input from Elspeth Garman.
> Added definitions relevant to radiation damage to cif_core.dic and associated units to templ_enum.cif

- cif_core.dic
These are the contents of the cif_ed.dic dictionary signed off by the nanED standards committee for incorporation into the core.
> Added terms relevant to electron diffraction.

- cif_core.dic
> Remove dot key data names

- cif_core.dic
- templ_attr.cif
Another round of minor changes to style as I work through the dictionary entries for Volume G typesetting.
> Editorial style changes to many definitions.

- cif_core.dic
(looks like a regexp substition of "Single" for "char" !)
> Spelling error in _chemical_formula.moiety

- ddl.dic
> Clarify the definition of the 'Range' content type

- cif_core.dic
See issue https://github.com/COMCIFS/dREL/issues/20 for more details.
> Replace 'missing' with '?' in dREL code

- cif_core.dic
and added _cell.formula_units_Z_details in accordance with new guidance from Commission on Crystallographic Nomenclature. Page numbers in journal reference (Brock,2025) to be updated when known.
> Modified range and extended definition of _cell.formula_units_Z
