- cif_core.dic
- cif_ms.dic
- cif_pow.dic
- cif_pow_multiphase.dic
- cif_twin.dic
- ddl.dic
This pull request contains the following changes:
1) The _type.dimension data items were enclosed with single quotation marks to specify that they are strings and not arrays;
2) The definition of URI was corrected (changed to "Uniform Resource Identifier");
3) Tab symbols were replaced with spaces;
4) The '_alias.definition_id' and '_category_key.name' data items were placed inside loops as required by the DDLm dictionary.
5) Adding the _symmetry_Int_Tables_number and _symmetry_equiv_pos_site_id aliases to the cif_core.dic,
6) Adding the _pd_instr_monochr_pre_spec and _pd_instr_monochr_post_spec aliases to the cif_pow.dic.
> Cif2 conversion: various small corrections

- cif_core.dic
Adding mandatory quotes around the values of the type dimension data item.
Adding commas instead of spaces as separators as discussed in issue #31.
> Cif2 conversion type dimension fix

- cif_core.dic
Several data items contained seemingly incorrect type purpose based on the fact that the dictionary already contained associated standard uncertainty data items. This fixes several inconsistencies mentioned in #82.
> Changed: changed the purpose of several data items to 'Measurand'

- cif_core.dic
- ddl.dic
Implementing changes discussed in issue #104.
This entails:
- Addition of the DEFINITION_REPLACED category;
- Removal of the _definition.replaced_by data item;
- Modification of existing definitions in the 'cif_core.dic' dictionary in regards to the changes.
Please note, that the _definition_replaced.by description text has been slightly modified to refer to the data items themselves and not the data names as being deprecated.
> Added the DEFINITION_REPLACED category

- cif_img.dic
- cif_ms.dic
- cif_rho.dic
- ddl.dic
Slightly updated the description of the 'Dimension' content type.
Updated the rest of the dictionaries to adhere to agreed upon notation.
Corrected several list values in the cif_ms.dic  to adhere to the CIF2 syntax.
> Cif2 dimmension notation fix up

- cif_img.dic
- cif_rho.dic
The cif_rho.dic and cif_img.dic were updated to adhere to the CIF2 format syntax.
Minor data modifications in regards to the recent changes in DDLm were also applied.
> Converting cif_rho.dic and cif_img.dic dictionaries to CIF2

- cif_core.dic
This PR corrects SU-related issues discussed in #82 
The solution includes:
- removing the '_chemical_conn_bond.distance_su' data item;
- changing the purpose of the '_diffrn_radiation_wavelength.value' data item from 'Number' to 'Measurand';
- adding the '_diffrn_radiation_wavelength.value_su' data item.
Please review if the definition of the '_diffrn_radiation_wavelength.value_su' data item seems sufficient.
> Correcting SU-related issues

- ddl.dic
Changed: added the new description for the 'Key' type purpose and changed the purposes of several data items in the DDL.dic to avoid conflicts with the new description.
This PR implements changes agreed upon in issue #108.
> Added new description of the 'Key' type purpose

- cif_core.dic
- ddl.dic
It seems that in one of the pull requests I have accidentally introduced a faulty date value (2019-14-02). Sorry for that. Also, since both the 3.13.2  and 3.14.0 revision were release on the same day, I have merged them into a single one (3.14.0).
> Correction of an invalid dictionary audit date

- cif_core.dic
- templ_attr.cif
Corrected multiple data item definitions to be compliant with the declared purpose. This included:
1. Changing the purpose of multiple data items from 'Encode' to 'Link';
2. Removing the _name.linked_item_id data item from the definition. The _diffrn_scale_group.code and _diffrn_standard_refln.code data items as well as the atom_site_label save frame were affected.
This PR solves issues #73 and #124.
> Corrected the purpose of data items with links to other data items

- cif_core.dic
`cif_core.dic` has `_dictionary.uri` of `www.iucr.org/cif/dic/cif_core.dic`, which lacks a scheme prefix (i.e. `http://`) to conform to [RFC 3986](https://tools.ietf.org/html/rfc3986). Moreover, this URI does not resolve. Thus I suggest using GitHub URI (`https://raw.githubusercontent.com/COMCIFS/cif_core/cif2-conversion/cif_core.dic`) as `_dictionary.uri` for this dictionary.
> Using a resolving URI for cif_core.dic

- ddl.dic
> Using an URI to fetch raw CIF contents for ddl.dic

- cif_core.dic
The ``_geom_hbond.angle_DHA_su`` data item was incorrectly assigned the same definition as the ``_geom_hbond.angle_DHA`` data item. This PR adds the proper definition.
> Correction of the _geom_hbond.angle_DHA_su definition

- ddl.dic
Changed the purpose of a dREL method in the definition of the `_dictionary_valid.application` data item from '`Definition`' to '`Evaluation`'. This closes issue #138.
> Fixed: corrected the method purpose of _dictionary_valid.application

- cif_img.dic
This PR resolves issue #153.
It should be noted, that in addition to the content type change an enumeration range of ``0.0:`` was also added base on the restrictions of the ``Count`` content type. It is not entirely clear if the assigned range is a correct one.
> Change the content type of pixel bin size data items to allow floating-point values

- cif_img.dic
The loop is needed to properly document additional changes to the dictionary (i.e. the removal of the "Count" data type).
The audit history compiled so far was based of GitHub logs and as such may be erroneous/incomplete. Please review and change accordingly if needed.
> Added the DICTIONARY_AUDIT loop in the 'cif_img.dic' dictionary

- cif_core.dic
- cif_img.dic
- cif_ms.dic
- cif_pow.dic
- ddl.dic
- templ_attr.cif
This PR implements changes outlined in issue #150.
The types were marked as deprecated in the ``type.contents`` definitions by simply adding a '(deprecated)' string to their human-readable descriptions. Please modify accordingly if this is insufficient.
> Deprecated 'Count' and 'Index' content types

- cif_img.dic
The ``_diffrn_scan_frame.integration_time`` and ``_diffrn_scan_frame_monitor.integration_time`` data items contained a strange typo (``integration`` ->``Integeregration``).
> Corrected a typo in the integration time object ids

- cif_core.dic
- cif_core.star2.dic
- cif_core_ddl1.dic
When `a` is parallel to `x`, `b` needs to be in the `xy` plane.
The `b in yz` orientation is impossible when gamma != 90deg.
> Fix example of _atom_sites_Cartn_transform_axes

- ddl.dic
When a data name is deprecated, with no alternative, a value of '.' is used.
> Explain meaning of '.' for data name deprecation

- ddl.dic
This is carried out in accordance with the decision of the DDLm group, see message https://www.iucr.org/__data/iucr/lists/ddlm-group/msg01560.html and subsequent messages in that thread.
> Deprecate xref datanames

- cif_core.dic
Although this merge changes datanames that were created a month ago, the dictionary hasn't been officially released or a new version provided, so I think this should be fine.
> Removed 'name' from facility and beamline datanames as redundant.

- cif_core.dic
- ddl.dic
A number of items are obsolete in DDLm:
1. Save frames. DDLm aims to be format-agnostic. All references to save frames and ref-loops have been removed, except for import statements for which a save frame reference is currently unavoidable
2. LOOP category. No official dictionary has ever used more than 1 level of looping, so there is no need for such attributes, which are also CIF-format-specific.
3. Complex data types. Data types of the form 'Type1|Type2' to indicate that an item could have more than one type are not used, are complex to implement, and so have been removed. Data types of the form List(Type2,Type3,...) to indicate List objects composed of a tuple of values, each of potentially different types, have been removed. These were almost exclusively used for synthetic keys, which …
> DDLm rationalisation

- ddl.dic
As discussed in ddlm-group, clarify the relationship between SU data names and measurand data names and how they may be presented in a data file.
> Clarification of Measurand - SU data item relationship.

- ddl.dic
The 'file' index of the `_import_details.single_index` data item should allow not only URI values, but also URI reference values. Based on this, I replaced the description for this index with the first line of the `_import_details.file_id` data item.
> Update the _import_details.single_index data item description

- cif_core.dic
- ddl.dic
- templ_attr.cif
This PR solves issue #194 by removing the default value of the `_units.code` data item ('`arbitrary`') and adding the `none` units to the definitions of multiple dimensionless data items. The definitions of several `_refine_diff.density_*_su` data items were also modified by copying the dREL methods for measurement units resolution from the main items that they are linked to (`_refine_diff.density_*`).
> Remove default units code

- ddl.dic
This PR improves the definition of the DICTIONARY_VALID category by explicitly stating that the validation rules described by data items in this category apply only to Reference and Instance dictionaries.
> Improve dictionary valid description

- cif_core.dic
This PR fixes a few misspelt data names in the newly added data item definitions.
> Fix misspelt data names

- ddl.dic
This PR updates the definition of 'Uri' content type to explicitly state that it allows URI-reference values as discussed in issue #191. Please also note, that changes proposed in this PR require some additional minor changes to the description of the `_alias.dictionary_uri` data item to indicate whether it refers to an absolute URI or an URI reference (see issue #191 for a more detailed explanation).
> Update the definition of the 'Uri' content type

- cif_core.dic
- templ_attr.cif
This PR fixes a few minor issues in the descriptions of the `ATOM_SITES_CARTN_TRANSFORM` category and the `_atom_sites_fract_transform` data item. It seems that in these description the coordinate systems were accidentally switched.
> Fix ATOM_SITES_CARTN_TRANSFORM description

- cif_core.dic
- templ_attr.cif
- templ_enum.cif
This PR addresses several minor typographical issues :
- Fixes a few typos ("eflections" -> "reflections", "interpanar" -> "interplanar", etc.);
- Homogenizes the descriptions of the SU data items;
- Homogenizes the descriptions of the `_journal_date.*` data items.
> Fix typos in CIF_CORE

- .github/workflows/main.yml
- cif_core.dic
A DDLm check action has been added. A number of minor changes were required to the core files to bring them into conformance:
- data names should not be aliased to themselves
- A data name should be `_type.purpose` 'Link' if it refers to a parent data name
> Add automated check of DDLm conformance after fixing minor errors

- cif_core.dic
This pull request replaces `_model_site.adp_eigen_system` with separate eigenvalue and eigenvector data names. I have opted to remove eigen_system completely, even though that would normally be a violation of standard rules, because eigen_system is nowhere used in the wild. 
Please comment on whether it would be more appropriate instead to use the `definition_replaced.by` attributes and not remove the eigen_system data name.
> Replaced model_site.adp_eigen_system

- cif_core.dic
This PR updates the definition of the `_journal_index.type` data item to match the description in ITC Volume G (2005), section 3.2.5.4.
I would have also adapted the 3.2.5.2 example to the `JOURNAL_INDEX` category definition, however, I was unsure if this is allowed (the current definition of the `_description_example.case` data item seems to imply that this item should only be used in data item definitions).
> Updated the _journal_index.type data item definition

- ddl.dic
This removes a contradiction due to the default value of `_dictionary_valid.option` (#212) and prepares for potentially removing `_dictionary_valid.application` altogether (#211).
> Added explicit scope, option attributes to dictionary_valid.

- ddl.dic
Addresses issues #220 and #221
> Clarified use of description_example and _description.text.

- ddl.dic
As discussed in #211 and no objections from ddlm group or cif-developers.
> Deprecate dictionary_valid.application

- cif_core.dic
Removed the _type.dimension attribute from the definition of the _refln.form_factor_table data item since it is not applicable
to the "Table" content type.
> Removed the _type.dimension attribute from the definition of the _refln.form_factor_table data item

- ddl.dic
The `DICTIONARY_VALID` loop was updated in the following ways:
1. The category names in the attribute list were sorted in an alphabetical order to improve readability. Data item names were not reordered in case there already was some kind of implicit ordering (i.e. in decreasing importance in case of mandatory/recommended items).
2. The `CATEGORY_KEY` category was removed from the list of items that are recommend in the category scope since the only item in this category is already explicitly provided in the same list.
3. The `DESCRIPTION_EXAMPLE` category was marked as forbidden in the dictionary scope.
> Updated the DICTIONARY_VALID loop

- ddl.dic
Make sure it is clear that child categories are included when a category is given in the list of attributes in the dictionary_valid list.
> Clarify meaning of _dictionary_valid.attributes

- cif_core.dic
The original description was incorrectly referencing non-existent data items `_diffrn_source.facility_name` and `_diffrn_source.beamline_name` instead of `_diffrn_source.facility` and `_diffrn_source.beamline` respectively.
> Update the description of the _diffrn_source.make data item.

- templ_attr.cif
The incorrect revision date was introduced in PR #202.
> Correct the revision date of the save_aniso_UIJ_su save frame.

- ddl.dic
This PR fixes several minor inconsistencies in the definitions. Main changes:
- Description of the `_type.definition` attribute was updated to state that the attribute is also applicable to the Array container type (the same thing is already stated in the definition of the 'Dimension' type).
-  The term "attribute dictionary" in the definition of the `_type.container` attribute was replaced with the more specific "DDLm Reference Dictionary". The same term was already used in a similar manner in the definition of the `_type_purpose.attribute` attribute.
- The text in the `_type_purpose.attribute` attribute was slightly realigned for readability.
> Adjust attribute definitions

- cif_core.dic
This PR fixes the units of measurement of the `_diffrn_radiation_wavelength.value_su` data item. Note, that the related `_diffrn_radiation_wavelength.value` data item already had the correct units.
> Change _diffrn_radiation_wavelength.value_su units

- cif_core.dic
This PR fixes the `_exptl_absorpt.correction_t_min` data item description which was most likely accidentally incorrectly copied form the `_exptl_absorpt.correction_t_max` data item.
> Fix the description of the _exptl_absorpt.correction_t_min data item

- cif_core.dic
- ddl.dic
This PR unifies the spelling of certain *(mostly CIF-related)* words to match the one presented in the CIF 2.0 paper [1]. Additional notes:
- In a few places the term "data name" (CIF tag) was changed to "data item" (CIF tag + CIF value).
- The date was removed from the usage example of the `_audit.update_record` data item since a separate looped data item (`_audit.creation_date`) is now the preferred way of specifying the date.
[1] http://scripts.iucr.org/cgi-bin/paper?aj5269
> Homogenise spelling of terms

- templ_enum.cif
This PR resolves issue #238 as suggested in the related discussion. Main changes:
- Colour value 'unknown' was changed to CIF special value '?' in the 'colour_hue' save frame.
- Colour value 'magenta' was changed to 'violet_magenta' in the in the 'colour_hue' save frame.
- Colour value 'steel_grey' was changed to 'grey_steel' in the in the 'colour_hue' save frame to be similar to other colour names that are already used (i.e. 'blue_steel').
- Colour 'grey_steel' was added to the 'colour_RGB' save frame. I was not able to find a definitive definition of steel grey/grey steel colour so please change the RGB code if needed.
I also reformatted the 'colour_hue' and 'colour_RGB' save frames to follow the DDLm dictionary style guide [1] since it is much more readable.
[1] …
> Fix colours in 'templ_enum'

- cif_core.dic
- ddl.dic
This PR changes the previously assigned version numbers to the SemVer 2.0.0 format [1] to satisfy additional GitHub Action check that would be introduced by merging a PR [2] in the dictionary_check_action repository. 
The SemVer format is generally compatible with the DDL 'Version' data type, although, slightly stricter in its syntax. For example, it requires all 3 version components to always be present ("1.0.0" is OK, but "1.0" is not) and does not permit leading zeros  ("3.0.5" is OK, but "3.0.05" is not). Although these type of requirements are not (yet) mandated by the DDL reference dictionary, they do help with keeping consistent version numbers.
If such additional version number requirements are not desired, just close this PR and let me know so I could patch the …
> Homogenise dictionary version numbers to the SemVer 2.0.0 format

- cif_core.dic
- templ_enum.cif
This PR resolves issue #71. Please note, that I also changed the data type of the `_atom_site.Wyckoff_symbol` data item from `Code` to `Text` to make it case sensitive (and match the definition of the `_space_group_Wyckoff.letter` data item). I guess for most "custom" enumeration values the distinction between lower/upper letters is not important (i.e. Uijo), however, in this instance the enumeration values are taken from an external source and thus it might be better to restrict them to the original (lower) case.
> Redefine the _atom_site.Wyckoff_symbol data item as an enumerator

- ddl.dic
This addresses the issue that certain values in DDL1 dictionaries were case-sensitive but conventionally did not contain spaces (such as atom labels). As no such type currently exists in DDLm this adds such a type to enable proper compatibility.
> New text type

- templ_attr.cif
- templ_enum.cif
This PR:
- Updates the version number string in template files to conform to format used in other dictionaries.
- Updates the formatting of the `DICTIONARY_AUDIT` loop to follow the DDLm dictionary style guide.
- Changes the DDLm dictionary conformance version to 4.1.0 (latest available at the time).
Also note, that one version number in the `DICTIONARY_AUDIT` loop of the `temp_enum.cif` file had to be changed from 1.0.1 to 1.1.0 in order to avoid duplicate loop key values.
> Fix dictionary audit loop in template files

- cif_core.dic
This PR fixes the `_exptl_crystal.colour` data item example case by changing it from a string to a proper CIF2 list. 
The `_exptl_crystal.colour` data item might get further modified in the future (see issue #189), however, this fix will at least allow the dictionary to properly validate for now.
> Fix the _exptl_crystal.colour data item example case.

- cif_core.dic
These data names should not have associated SU values. This is in keeping with DDL1 behaviour.
> Changed _gt/_lt data names to 'Number' type

- cif_core.dic
This PR homogenises the definitions of `_journal.issue` and `_citation_journal_issue` data items. Note the example case, that was added to justify the 'Text' content type.
> Homogenise definitions of journal issue items.

- ddl.dic
This PR updates the descriptions of the `_enumeration.default` and `_description_example.case` data items to explicitly list
all the constraints that they inherit from the defining item.
> Update descriptions of items with implied constraints

- cif_core.dic
This PR homogenises the definitions of `_citation.year` and `_journal.year` data items.
Note, that the `_enumeration.range` attribute with the value `1700:2100` was not copied to both of the items, but instead removed altogether. The lower limit of `1700` might make sense for crystallography related publications, but the citation category may potentially reference non-crystallography related books or papers that were published prior to 1700 (i.e. paper that the synthesis of the compound was first described in). The upper limit of `2100` could be used for validation for the next 80 years, however, semantically this limit looks quite strange and should probably be better implemented as a stand-alone subroutine, rather than hardcoded into the dictionary.
Please let me know if the …
> Homogenise the definitions of publication year items

- cif_core.dic
This PR resolves issue #277 by adding an upper enumeration limit of 192 to the definition of the _space_group_symop.id data item.
> Add an upper limit to _space_group_symop.id

- .github/workflows/main.yml
- cif_core.dic
This fixes the incorrect order in two su data names brought about by an incorrect pretty printer/linter. It also fixes the workflow which was necessary because of an update to the linter used to check layout.
Note that the automated check will fail until the workflow is fixed by this PR.
> Fix for incorrect ordering of 2 su data names in dictionary.

- cif_core.dic
This PR changes the content type of the `_journal.paper_doi` data item from 'Code' to 'Text' and adds an example case as discussed in issue #275.
Note, that I used a fake resolvable DOI [1] in the example (10.5555/12345678) to avoid unwanted/unexpected traffic to any real publication that may arise from it being included in a publication. Please change it to a more relevant one if needed.
[1] https://www.crossref.org/blog/doi-like-strings-and-fake-dois/
> Homogenise DOI data items

- ddl.dic
This PR fixes a minor typo in the definition of the `_name.linked_item_id` data item.
> Update the description of the _name.linked_item_id data item.

- templ_enum.cif
Enumerate the allowed units for mass absorption coefficients.
Needed by https://github.com/COMCIFS/Powder_Dictionary/pull/19
> add units for mass absorption coefficients

- templ_enum.cif
See [here](https://github.com/COMCIFS/Powder_Dictionary/blob/master/cif_pow.dic#L452) for usage of these units in the TOF calibration equation.
> Add units for time-of-flight calibration equation.

- cif_core.dic
This addresses and resolves #168. The cif_core dictionary management group had no objections to this course of action.
Closes #168.
> Fix diffrn radiation

- cif_core.dic
Begins to address #304 
I've added `ATOM_ANALYTICAL_SOURCE` and associated data names. Also added the beginnings of `ATOM_ANALYTICAL` so I could properly nest everything.
`ATOM_ANALYTICAL_SOURCE` should contain all the necessary data names. More to come for `ATOM_ANALYTICAL`.
I think I've done it correctly.
> Add ability to record elemental composition of specimens

- cif_core.dic
The `_diffrn_reflns.limit_min` and `_diffrn_reflns.limit_max` data items were assigned the Real content type. I assume that this was a mistake since everywhere else throughout the dictionary Miller indices are defined as Integers, e.g. even the individual `_diffrn_reflns.limit_{h|k|l}_{min|max}` data items used to populate the `_diffrn_reflns.limit_{min|max}` matrices.
> Fix the content type of the _diffrn_reflns.limit_{min|max}

- ddl.dic
This PR resolves issue #268.
A new DDLm version number is probably not required since version 4.1.0 has not yet been formally released.
> Explicitly allow half-bounded enumeration ranges

- cif_core.dic
Will close #291 
As noted above:
>the `_diffrn_standards_*` data names in DDL1 have been transformed into `_diffrn_standard.*` data names in DDLm, i.e. the `s` has been dropped. This breaks the convenient heuristic that valid DDL1 data names can be created by simply replacing the `.` with `_` in DDLm. ... I can see no useful reason for this change.
The DDL1 dictionary is [here](https://github.com/COMCIFS/DDL1-legacy-dictionaries/blob/28e20dc928790dceb889716d2bed435fc10c4c79/dictionaries/cif_core.dic#L6285).
> rename DIFFRN_STANDARD and data names to DIFFRN_STANDARDS

- cif_core.dic
will close #240 
Wording guided by https://blog.apastyle.org/apastyle/2017/05/whats-in-a-name-authors-with-only-one-name.html
> update author.name-type data items to specify single-name author formatting

- ddl.dic
This PR addresses issue #312.
Note that in the new definition the version string part were changed from `<major>`.`<version>`.`<update>` to `<major>`.`<minor>`.`<patch>` so they would match up with the SemVer specification. This can be reverted if preferred.
> Clarify the definition of the "Version" state in _type.contents

- cif_core.dic
- ddl.dic
- templ_enum.cif
This PR resolves issue  #205.
Note that I also slightly changed the phrasing in the description of the `REFINE_DIFF` category. Specifically, I changed the phrase "electron density limits" to "scattering density limits" since the data items in the category can describe both electron densities and scattering length density. @jamesrhester , @rowlesmr  is the term `scattering density limits` appropriate or is there a better one?
> Fix scattering density units in dREL

- cif_core.dic
This PR changes the spelling of several dREL names so they would match the definition id.
> Fix dREL names of _audit_support.funding_organization_*

- cif_core.dic
This PR addresses issue #189.
While drafting this PR I made a few assumptions that should be addressed before merging:
- I introduced quite a strict format for the color text string based on the values of items from the `EXPTL_CRYSTAL_APPEARANCE` category to mimic the format of the removed list data structure. However, alternatively we might want to remove any formatting requirements on the field so it could also be used as a catch-all field (read `special_details`) for crystal colour data. There are a few instances in the COD of entries which seemingly cannot be described by the items from the `EXPTL_CRYSTAL_APPPEARANCE` category (e.g. `dichroic dark purple/pale blue`), but they are not very numerous. Should I remove the formatting requirements (the dREL part can still remain as a …
> Change the _exptl_crystal.colour data item from a list to a text string

- cif_core.dic
According to a report by a subcommittee on atomic displacement parameter nomenclature [1], the term "atomic displacement parameters" should be used instead of "temperature factor parameters". This seems to have already been mostly done throughout the dictionary text, however, a few instances still remained. 
[1] https://scripts.iucr.org/cgi-bin/paper?es0238
> Remove temperature factor terminology

- cif_core.dic
Not sure if this is significant, but the definitions of `_exptl_crystal.size_mid` differ slightly in CIF_CORE and mmCIF [1]. The difference is in a single word ("medial" vs "median"), both options of which seem to mean the same thing (to my level of understanding). Feel free to reject the PR if the change is indeed only nominal.
[1] https://mmcif.wwpdb.org/dictionaries/ascii/mmcif_std.dic
> Reword definition of _exptl_crystal.size_mid to match that provided in mmCIF

- cif_core.dic
This PR introduces the `_citation.URL` data item addition of which was requested on the IUCr website (https://www.iucr.org/resources/cif/dictionaries/new-item/cif_core/_citation_url).
I also added the `_journal.paper_url` since it serves a similar purpose.
> Add the _citation.URL and _journal.paper_url data items

- cif_core.dic
- examples/complex-compositional-disorder.cif
- examples/simple-compositional-disorder.cif
This PR tries to at least partially address issue #251. Please check if the rewording is suitable.
I also added two example CIF files that describe compositional disorder using the `_atom_site.disorder_*` data items. These examples were created from legitimate CIF files found in the COD database and represent the already adopted usage practices. I did do some editorial changes like remove most of the data items unrelated to the specific example and update the the data names to their newer dotted versions, but did not modify the semantics (the disorder markup was introduced by the original authors of the CIFs). Hopefully, these can be used to create a suitable example which was requested in https://github.com/COMCIFS/cif_core/issues/251#issuecomment-981221147.
Also, I noticed that the …
> Allow explicit compositional disorder markup

- cif_core.dic
This PR explicitly add `_diffrn_source.details` to the list of items that replace `_diffrn_source.description` since this item was already mentioned in the human-readable part of the definition.
> Explicitly add _diffrn_source.details to the list items that replace _diffrn_source.description

- cif_core.dic
This PR introduces two bibliography-related data items addition of which were requested at the IUCr website:
* `_journal_article_number` (https://www.iucr.org/resources/cif/dictionaries/new-item/cif_core/_journal_article_number).
* `_journal_article_page_count` (https://www.iucr.org/resources/cif/dictionaries/new-item/cif_core/_journal_article_page_count).
I slightly renamed the data items to follow the naming conventions of other data items:
* `_journal_article_number` to `_journal.paper_number` to match `_journal.paper_DOI`.
* `_journal_article_page_count` to `_journal.paper_pages` to match `_journal.suppl_publ_pages`.
Of course, the original names could be used if preferred.
> Add journal article number and page count

- cif_core.dic
The old URL [1] no longer resolves to the desired content. I checked the WayBackMachine [2] and found an updated URL [3] which seems to point to the same content. Also added a DOI to the cited paper.
[1] http://www.chem.qmul.ac.uk/iupac/stereo/index.html
[2] https://web.archive.org/web/20060820142257/http://www.chem.qmul.ac.uk/iupac/stereo/index.html
[3] https://iupac.qmul.ac.uk/stereo/
> Fix stereochemistry terminology url

- cif_core.dic
The Open Funder Registry repository seems to have been moved from GitHub to GitLab. The GitHub repository is still available, however, it is archived and is no longer maintained.
> Update URL of the Open Funder Registry repository.

- cif_core.dic
This PR resolves #316.
Few additional notes on the changes:
* `_journal_index.id` was left unchanged for now and a separate issue was filed to address it (#345).
* `_journal_index.id` was left unchanged for now and a separate issue was filed to address it (#346).
* `_citation.book_id_isbn` was assigned the `Code` content type since ISBN consist only of digits and dashes thus case-sensitivity is not an issue.
* `_chemical.identifier_inchi` and `_chemical.identifier_inchi_key` were assigned the `Word` content type since spaces are not allowed in these identifiers and case-sensitivity may be important (the previously assigned content type was `Text` which is also case-sensitive).
> Change identifiers to word

- cif_core.dic
Some time ago it was agreed to make all enumeration values case-sensitive (https://github.com/COMCIFS/cif_core/issues/38#issuecomment-315652558). The consensus might have changed after that,  but currently the majority of all items with enumeration values adhere to this rule and are case-sensitive (either `Text` or `Word`).
This PR updates the definitions of 5 items that currently deviate from this rule to be case-sensitive in order to be consistent.
> Make enum case sensitive

- cif_core.dic
- examples/complex-compositional-disorder.cif
- examples/simple-compositional-disorder.cif
This PR adapts the positional disorder description example which was originally provided in DDL1 version of the dictionary as discussed in issue #251.
I also added a new example of a compositional disorder description based on the `simple-compositional-disorder.cif` example file.
> Add disorder example from ddl1

- cif_core.dic
This PR contains the initial attempt at resolving issue #169.
Also, note that this PR adds the 'Other' relation type to accommodate a more flexible linking to databases that do not contain crystallographic data.
> Add database related relation other state

- cif_core.dic
Resolves #346.
This PR removes the outdated dREL from `_citation_author.key` and `_citation_editor.id`.
Note, that these items are still not explicitly specified as category keys in the definitions of  corresponding categories, but this should be addressed in a separate PR if needed.
> Remove outdated dREL and update the content type in several definitions

- cif_core.dic
Recent changes to the author categories introduced author identifiers, which were key data names. However, legacy data files will not have this data name and thus fail validation. The current changes introduce dREL methods that provide default values. Closes #103 .
Note that the dREL is implemented using a `Definition` method rather than an `Evaluation` method, as the `Evaluation` method would imply a single correct value, and validation would therefore fail if the file contained any values for the identifiers that were not the row numbers. `Evaluation` methods were appropriate for `_space_group_symop.id` because legacy CIFs used the `space_group_symop` category row number to refer to symops.
The `Definition` method creates a new value for the default value for each row. This is an …
> Provide default values for author identifiers

- templ_enum.cif
There was a bunch of trailing whitespace in templ_enum.cif.
I've just removed it all. No information was changed.
If this gets merged first, it may clean up the diff for #375
> removed trailing whitespace in templ_enum

- templ_enum.cif
will close #374
Divided hi_ang_Fox_c2 by 10 and hi_ang_Fox_c3 by 100
The diff is really messy, as there were, apparantly, a lot of trailing whitespace throughout the file.
> Altered hi_ang_Fox_c2 and hi_ang_Fox_c3 magnitudes

- templ_enum.cif
Closes #383.
I chose to use the more precise value of V since it matches the one provided in Table 4.4.4.1 of ITC Vol. C (2004). There, the value is given as -0.3824(12).
> Update the values for V2+, V3+ and V5+ in the 'length_neutron' save frame

- cif_core.dic
> Rewrite the _atom_type.radius_contact evaluation method as a definition method.

- cif_core.dic
Will close #393 
Now an `atom_type` can have a specific isotope.
This will eventually allow for default scattering lengths to be enumerated, if #399 is accepted.
> Add `_atom_type.mass_number`

- cif_core.dic
Will close #357, eventually.
I've added the ability to record an arbitrary number of coefficients for the conventional sum-of-Gaussians (a la Cromer-Mann and Wassimier-Kirfel), and the exponential polynomial model (cf Fox), as well as an inverse Mott-Bethe relationship parameterised as a sum of Gaussians.
Each of the models also has an upper/lower limit, so that an element can have multiple models associated with it for different s ranges.
If this looks OK, I'll have a go at looking at 
>The tables in `templ_enum.cif` would then have a list of numbers for each atom type and we would change the dREL for `_refln.form_factor_table` to access `_atom_type_scat.Gaussian_coeff`.
> Add ability to record an arbitrary number of form-factor coefficients

- cif_core.dic
- templ_attr.cif
Discussion started in #409
I noticed that that the `_atom_type_scat.hi_ang_fox_c?` and `_atom_type_scat.cromer_mann_b?` dataitems had units which didn't match what they should be. So I changed them.
I also updated the descriptions to give equations so there is more clarity behind the use of the values.
> Fix scattering factor units

- ddl.dic
Will close #377.
Added the ability to record authors of a dictionary. Does there also need to be a `DICTIONARY_AUTHOR_ROLES` category? I think that may overcomplicate things, but it's an option.
> Add `DICTIONARY_AUTHOR`

- ddl.dic
- templ_enum.cif
will close #409 
as mentioned in https://github.com/COMCIFS/cif_core/issues/409#issuecomment-1576037690
Where a dataitem consists of an arbitrary number of values, or a mixture of values with different units, use `.` to indicate that the user (either a person or a program) must decide which units to apply to any single value taken from the item.
> add unit to allow `_units.code` to express and arbitrary mixture of units

- cif_core.dic
Closes #409.
Specifically, this PR changes the units of some data items to 'unspecified'. The items in need of this change were taken from the a comment by @rowlesmr in issue #409 (https://github.com/COMCIFS/cif_core/issues/409#issuecomment-1574719776).
However, I did not modify two of the items:
* `_atom_type_scat.versus_stol_list`. This item will be overhauled to return its compatibility with DDL1 (see #216).
* `_refln.form_factor_table`. Here the units seems to depend on the type of radiation. If I correctly understand the dREL code in case of "neutron" we end up with `femtometres` and otherwise we end up with `none`. So maybe we could have a `Definition` method  that assigns units based on this criteria (as is already done in the case of `_refine_diff.density_max_su`).
> Change the units of some data items to 'unspecified'.

- ddl.dic
Will close #416
It is "The" DOI, as there should only be one (AFAIK).
It's "the DOI for this dictionary", as it should point to the actual dictionary file (https://github.com/COMCIFS/cif_core/issues/416#issuecomment-1594442167)
It's of type.content `Word`, as the DOI probably shouldn't be given as a URI ("I would (personally) prefer that _dictionary.DOI be given as 10.1107/cifdic_000002 etc., but that does run counter to CrossRef guidance and almost-universal practice." https://github.com/COMCIFS/cif_core/issues/416#issuecomment-1593324634)
> add _dictionary.doi

- ddl.dic
The GitHub actions currently fail due to `_dictionary.doi` data item not being included in our dictionaries. In case we do not yet have a suitable DOI to be included in the dictionaries, we can simply silence the warning by filtering it out in the https://github.com/COMCIFS/dictionary_check_action repository. Should suppress such warnings for now?
> Add _dictionary.doi to the list of items recommended in dictionaries

- cif_core.dic
- ddl.dic
- templ_attr.cif
- templ_enum.cif
This is needed to clearly delineate new changes from those already in the 3.2.0-rc release branch.
> Update dictionary version numbers and changelog messages.

- ddl.dic
This PR removes the sentence "If there are multiple authors, _dictionary_author.name is looped with _dictionary_author.address".
Note, that the `_dictionary_author.address` attribute is purposely not defined in the dictionary and the fact that multiple author names should be looped is already somewhat obvious.
> Update description of _dictionary_author.name.

- cif_core.dic
Prompted by discussion https://github.com/COMCIFS/cif_core/pull/430#issuecomment-1605442143
`_exptl_absorpt.coefficient_mu` was defined as `Number`, but the description of this item is given in terms of values which are `Measurand`s. `_exptl_absorpt.coefficient_mu` was changed to `Derived` `Measurand`, and the SU data item was added.
In the process, I noticed that a bunch of SU data items' `_type.source` was `Related`, which doesn't seem to link up with the description of `Related`, so I changed them all to match the `_type.source` of the data item to which the SU belongs.
> Add  `_exptl absorpt.coefficient_mu_su`

- cif_core.dic
The 'Recorded' source is probably not very suitable, since this (almost) arbitrary id was neither observed, nor measured.
Edit: changed "recorded" to "measured".
> Change the source of _citation.id to 'Assigned'

- ddl.dic
This PR rewords some of the definitions as discussed in #437.
Specifically, it properly defines the *primitive* and *non-primitive* data items, and explicitly specifies that Definition methods should not be used on primitive items.
I was not sure if `Related` items should be considered *primitive* or *non-primitive*. I guess they should be handled in the same way ass `Assigned` values (*primitive*/*non-primitive* depending on the context).
> Describe primitive data items

- cif_core.dic
- templ_attr.cif
will close #439 
With moving `CELL` from `EXPTL` to `DIFFRN`, the related parameters should no longer be `Recorded`.
> Alter CELL-related saveframes from Recorded to Derived

- cif_core.dic
> Redefine _journal_index.id as 'Word' instead of 'Integer'.

- ddl.dic
The default class of 'Datum' is not allowed in definitions of the Reference dictionary.
> Add explicit definition class to items in the reference dictionary.

- cif_core.dic
The values of `_atom_site.type_symbol` should be used first when determining the values of `_atom_type.symbol` since the assigned types might differ from those derived from atom labels.
Since the dREL method for  `_atom_site.type_symbol` data item also derives the values from the values of `_atom_site.label`,  the updated dREL will still yield the same result in cases when the values of `_atom_site.type_symbol` are not explicitly defined.
> Update dREL evaluation method of the ATOM_TYPE category

- ddl.dic
to specify a double colon, and made some other essentially cosmetic style changes elsewhere.
> Corrected _dictionary.namespace definition 

- templ_attr.cif
This PR should be merged after merging PR https://github.com/COMCIFS/Modulated_Structures/pull/20.
According to the upcoming version of ITC Volume G, template dictionaries should not contain the _definition.id, _name.object_id or _name.category_id attributes. This PR removes this attribute.
> Remove the _name.category_id attribute from the 'matrix_w' save frame

- cif_core.dic
The InChI string had a trailing quote. The InChIKey incorrectly had a prefix and I did not seem to be correct in general (searching using this InChiKey yielded almost no results).
> Fix inchi examples

- cif_core.dic
The `_space_group_Wyckoff.id` and `_valence_ref.id` data items are a arbitrary keys that do not encode any other information.
> Change the purpose of several items from 'Encode' to 'Key'.

- cif_core.dic
Will close #463 
Modified category description to remove reference to looping, and referred to `DIFFRN_RADIATION_WAVELENGTH`, instead.
> Remove description of looping behaviour from Set category description

- ddl.dic
This PR updates the definition the definition of the `_enumeration_set.state` attribute to inherit the content type and other attributes from the defining data item. This is the same approach that was previously applied to the `_enumeration.default` data item. This change is needed so that enumeration values which are not compatible with the defining data items would be more easily detectable by standard validation procedures.
Actually, this change helped to uncover one such case in the DDLm Reference dictionary. The `_units.code` attribute is defined as having the `Code` content type that does not allow spaces, however, the same attribute also contains `photons per second` as one of the enumeration values (see related issues https://github.com/COMCIFS/cif_core/issues/303, …
> Update enumeration set state definition

- templ_attr.cif
- templ_enum.cif
The old dictionary URLs do not seem to resolve at all, e.g.:
* www.iucr.org/cif/dic/com_att.dic
* www.iucr.org/cif/dic/com_val.dic
> Change template dictionary URLs to the GitHub ones

- ddl.dic
This PR adds the `_type.dimension` attribute to the definition of `_import.get`. Since the `_type.dimension` attribute does not have a default value, it is not clear how `List`, `Array` or `Matrix` values without this attribute should be interpreted.
> Add the _type.dimension attribute to the definition of _import.get

- ddl.dic
This PR updates the `_method.expression` description to reflect its current use. Specifically, the attribute seems to now be used not only in item definitions, but also in category definitions (e.g. `GEOM_ANGLE` from the `CIF_CORE` dictionary).
> Update the definition of the _method.expression attribute

- ddl.dic
This PR explicitly specifies that the first part of a `Symop` values (e.g. `2` in `2_555`) must be a positive integer as opposed to any integer. This limitation is imposed since the `_space_group_symop.id` attribute can only have integer values in the range of [1, 230]. Even if the same content type is later on reused to represent magnetic or modulated structures, the symop id will most likely still not be negative or 0.
> Updated the description of the 'Symop' content type

- cif_core.dic
This PR clarifies the relationship between `_diffrn_refln.scale_group_code` and `_diffrn_scale_group.code` data items.
The previous definition of `_diffrn_scale_group.code` was slightly incorrect since it stated that:
```
The code must match a _diffrn_refln.scale_group_code in the DIFFRN_REFLN list.
``` 
while the actual relationship is the opposite -- item `_diffrn_scale_group.code` is the main one thus values of `_diffrn_refln.scale_group_code` must match the values of `_diffrn_scale_group.code`, but not necessarily the other way around.
> Update the definitions of `_diffrn_refln.scale_group_code` and `_diffrn_scale_group.code`

- templ_enum.cif
Closes #303.
The 'photons per second' units were renamed to 'photons_per_second' in the upcoming version 1.8.8 of the `cif_img.dic` dictionary [1] so the same change can be reflected in DDLm as well.
Although it is unlikely that the units will change again, we might want to wait until the release of version 1.8.8 just to be safe before merging this PR.
[1] https://github.com/yayahjb/cbf_imgcif_dictionary/tree/main
> Rename the 'photons per second' unit to 'photons_per_second'

- .github/workflows/main.yml
This PR updates GitHub actions to use Node.js v20 where possible.
`julia-actions/setup-julia` seems to not yet offer a version compatible with v20 (see https://github.com/julia-actions/setup-julia/issues/208).
> Update GitHub action dependencies

- ddl.dic
This PR attempts to specify how '.' and '?' CIF special values should be interpreted in the context of the `_alias.deprecation_date` attribute. The assignment of a default value of '.' (not deprecated) also seemed appropriate.
Suggestions are welcome.
> Update definition of the `_alias.deprecation_date` attribute.

- cif_core.dic
This PR supplements PR #479.
I accidentally left out several deprecated aliases since they belong to data items that have also been deprecated in DDLm (see `_definition_replaced.by` attribute). I think it is still make sense to assign the specific deprecation date to data names inherited from DDL1.
> Mark deprecated aliases that belong to deprecated data items

- cif_core.dic
This PR adds the `_atom_site_fract.symmform` and `_atom_site_aniso.symmform` data items (see discussion in [1]).
The definitions of these items were almost verbatim copied from the document attached in [1] with the following changes:
* Data item `_atom_site_fract.symmform` was renamed to `_atom_site.fract_symmform` (changed the placement of the dot). The category of this item was also changed from `ATOM_SITE_FRACT` to `ATOM_SITE`.
* The human-readable definition of `_atom_site_aniso.symmform` was changed to use the term "anisotropic displacement parameters" instead of "anisotropic thermal ellipsoid".
* Both items were assigned the "Assigned" `_type.source`.
* Both items were assigned the "Encode" `_type.purpose`. (I assume here that they are intended to be machine-parsable). 
Before …
> Add the `_atom_site_fract.symmform` and `_atom_site_aniso.symmform` data items

- cif_core.dic
I've removed the description of the dataitem to which the SU is linked from the description of the SU. The SU description now only references the dataitem to which it is linked.
This means that if you update the description of an item with an SU, the description of the SU is automatically correct.
eg
```
Standard uncertainty of the mean hydrostatic pressure
at which intensities were measured.
```
is now
```
Standard uncertainty of _diffrn.ambient_pressure.
```
I haven't altered any definition dates, as I don't think I substansively changed anything, but I can if desired.
> Harmonise SU descriptions.

- ddl.dic
> Update definition of the _alias.dictionary_uri attribute.

- cif_core.dic
This PR renames the dictionary following the conventions agreed upon in issue #488.
> Change the title of the dictionary to CIF_CORE

- cif_core.dic
This PR adds lower limits to stol and scat data items as discusses in https://github.com/COMCIFS/Electron_Density_Dictionary/issues/12#issuecomment-2101870311.
It did not add a new changelog message since these changes fall under the umbrella of earlier changes that have already been described (addition of the `ATOM_SCAT_VERSUS_STOL` category).
> Explicitly define stol and scat values in the as non-negative

- cif_core.dic
This PR renames the Head category as discussed in issue #488.
Note that since the Head category name is used in the import statements of multiple dictionaries, these should be updated as soon as possible after merging the PR. I will provide a list of PRs for the dictionaries in question in a separate comment.
The `ATOM_SCAT_VERSUS_STOL` data item update dates were changed since I somehow managed to set them a month in the future in my previous PR.
> Rename Head category to 'CIF_CORE_HEAD'

- ddl.dic
This PR adds _definition.update to the list of attributes mandatory for the 'Category' scope.
My two arguments in favour of this:
* The _definition.update is already mandatory in the 'Item' scope.
* Category definitions may also contain quite important information (e.g. key item declarations) so I think it would be useful to formally track this.
> Add _definition.update to mandatory category attributes

- cif_core.dic
This PR redefines the `_cell_measurement.wavelength` data item as a measurand and adds the corresponding SU item. While this data item is already deprecated, it makes sense to still correct this issue for consistency (`_cell_measurement.temperature`, `_cell_measurement.pressure` and the `_diffrn_radiation_wavelength.value` data item that superseded `_cell_measurement.wavelength` all allows SU values).
Note, that the definition of this data item in the DDL1 dictionary also did not allow SU value, but I have opened a separate PR in the DDL1 legacy dictionary repository to fix this (https://github.com/COMCIFS/DDL1-legacy-dictionaries/pull/9) that can be merged once/if this PR is approved.
> Redefine cell measurement wavelength as measurand

- cif_core.dic
This PR adds the `_audit_support.funding_organization_URL` and `_audit_support.special_details` data items. The suggested items would help with some real life cases that we have encountered while using the `AUDIT_SUPPORT` category.
The  `_audit_support.funding_organization_url` data item would be useful for at least two reasons. Firstly, the organization DOI may not always be available (e.g. if the organisation is not yet registered with CrossRef).  Furthermore, the organization DOI links to a JSON page which is machine-readable and quite informative, but not very human-friendly. Since these two data items are intended to serve slightly different purposes, I added a disclaimer to also include  `_audit_support.funding_organization_DOI` when possible.
The `_audit_support.special_details` is …
> Add more AUDIT_SUPPORT data items

- cif_core.dic
hkl are inadequate to identify reflections as twinning or incommensurate structures will cause them to be repeated. Note also that mmCIF already defines `_diffrn_refln.id`.
Changing the unique key for `refln` and `diffrn_refln` will not have any practical effect on legacy software as that software would have broken anyway in situations where hkl are repeated.
This fixes issue #499.
> Replace hkl with opaque identifiers for reflections

- templ_enum.cif
Lukas Palatinus requested the more detailed annotation of electrons_per_angstrom after extensive discussion within the 3DeD community as to the appropriate way to record the electrostatic potential, especially in constructing residual difference maps.
> Extended description of electrons_per_angstrom at community request

- ddl.dic
The Unicode symbols are already used throughout the CIF_CORE dictionary.
> Replace CIF notation with Unicode symbols in the DDLm reference dic

- templ_enum.cif
The new measurement unit electron volts per angstrom was added. These units are needed in Nudged Elastic Band (NEB) experiment to describe residual forces. These units are currently used in the development version of the CIF_TCOD_NEB dictionary (https://www.crystallography.net/tcod/cif/dictionaries/ddlm/cif_tcod_neb/cif_tcod_neb_0.1.0.dic , see definitions _tcod_neb_image.residual_forces, _tcod_neb_image.residual_forces_su).
> added new units - electron volts per angstrom

- cif_core.dic
A systematic refolding of the dREL code for readability is probably best made by automated means, however, I ran into these particular fragments while comparing definitions which are defined in coreCIF and then redefined in pdCIF.
> Refold some dREL code for readability

- cif_core.dic
In this particular case the dot makes it clear that the items belong to the same category.
> Use dot seprated names in data item descriptions

- cif_core.dic
These data names do not seem to be defined in any other CIF dictionary. Furthermore, the corresponding _cell_angle.beta and _cell_angle.gamma measurand aliases are not even defined in this cifCore dictionary.
The issue was originally noticed by @ml-evs.
> Remove the _cell_angle.beta_su and _cell_angle.gamma_su aliases
